language: cpp
compiler:
- gcc
- clang
before_install:
- sudo apt-get update
install:
- sudo wget http://mirrors.kernel.org/ubuntu/pool/universe/e/eigen3/libeigen3-dev_3.2.0-4_all.deb
- sudo dpkg -i libeigen3-dev_3.2.0-4_all.deb
- sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
- sudo apt-get install libboost-all-dev
- sudo apt-get install python-ply
- wget http://mirrors.kernel.org/ubuntu/pool/universe/c/cxxtest/cxxtest_4.0.3-2_all.deb
- sudo dpkg -i cxxtest_4.0.3-2_all.deb
script: make
branches:
  only:
  - master
notifications:
  recipients:
  - mail@malte-janduda.de
  email:
    on_success: change
    on_failure: always
